services:
  - type: web
    name: safitech-solutions
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: ADMIN_PASSWORD
        value: your_secure_password
